[platformio]
src_dir = .

[env:esp32_c3_rust]
platform = espressif32@^6.3.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_ESP32_C3_DEVKIT_RUST_1

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.15.5

build_src_filter = +<main.cpp>

board_build.partitions = partitions.csv
board_build.filesystem = spiffs